OPENAI_API_KEY = "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"
APP_PASSWORD = "bfi44chatVAN!"